<a href="https://colab.research.google.com/github/MihirPatel204/Healthify/blob/main/Data_Science/Learning_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learing Numpy Basics

### Making array with list


In [ ]:
import numpy as np

arr_1d = np.array([1,2,3,4,5])
print("array 1d: " ,arr_1d)

arr_2d = np.array([[1,2,3],[1,2,3]])
print("array 2d : \n" , arr_2d , "\n")

array 1d:  [1 2 3 4 5]
array 2d : 
 [[1 2 3]
 [1 2 3]] 



### Metric Genration

In [ ]:
# basic metrics of zeros, ones, randoms and in sequence form numpy in bulid methods.

zeros = np.zeros((2,4))
print("array of zeros : \n", zeros)

ones = np.ones((3,4))
print("array of ones : \n", ones)

randoms = np.random.random((3,3))
print("array of randoms : \n", np.floor(randoms * 100))

sequence = np.arange(1,10,2)
print("array in sequance : \n", sequence)

array of zeros : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
array of ones : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
array of randoms : 
 [[24. 53. 87.]
 [59. 95. 53.]
 [71. 55. 60.]]
array in sequance : 
 [1 3 5 7 9]


### Vector, Metric and Tensor

* vector is 1 dimension array  
* matrics is 2 dimension array  
* tensor is more than 2 dimension array

In [ ]:
vector = np.array([1,2,3])
print("vector : \n", vector)

matrix = np.array([[1,2,3],[1,2,3]])
print("matrix : \n", matrix)

tensor = np.array([[[1,2,3],[1,2,3]],
                    [[1,2,3],[1,2,3]]])
print("tensor : \n", tensor)

vector : 
 [1 2 3]
matrix : 
 [[1 2 3]
 [1 2 3]]
tensor : 
 [[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


### Array Properties

In [ ]:
# properties of the array in numpy

arr = np.array([[1,2,3],[9,8,7]])
print("Shape : ", arr.shape)
print("Dimension : ", arr.ndim)
print("Size : ", arr.size)
print("DType : ", arr.dtype)

Shape :  (2, 3)
Dimension :  2
Size :  6
DType :  int64


### Array Methods

In [ ]:
arr = np.arange(10)
print("original array : ", arr)

reshaped = arr.reshape(2,5)
print("reshaped array : \n", reshaped)

flattened = reshaped.flatten()
print("flattened array : \n", flattened)

#returns a view instead of copy
raveled = reshaped.ravel()
print("raveled array : \n", raveled)

#change dimension from (2,5) to (5,2) in example array
transposed = reshaped.transpose()
print("transposed array : \n", transposed)

original array :  [0 1 2 3 4 5 6 7 8 9]
reshaped array : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
flattened array : 
 [0 1 2 3 4 5 6 7 8 9]
raveled array : 
 [0 1 2 3 4 5 6 7 8 9]
transposed array : 
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


### Adding And Removing Data

In [ ]:
# combineing array
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 5, 6, 7, 8])

combined = np.concatenate((array1,array2))
print(combined)

#adding or Removeing element to array gives new Array

new_array = np.append(array1,10)
print("appending element in array", new_array)

new_array = np.insert(array2,1,4)
print("inserting element in array", new_array)

new_array = np.delete(array2,1)
print("deleting element in array", new_array)

[1 2 3 4 5 3 5 6 7 8]
appending element in array [ 1  2  3  4  5 10]
inserting element in array [3 4 5 6 7 8]
deleting element in array [3 6 7 8]


# Opration On Numpy Array

### Basic Slicing

In [ ]:
# Slicing in vectors
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])

print("Basic Slicing :", arr[3::])
print("Basic Slicing :", arr[3:7])
print("with steps : ", arr[1:9:2])
print("reverse : ", arr[::-1])
print("reverse slicing : ", arr[-5:-1])


Basic Slicing : [ 4  5  6  7  8  9 10]
Basic Slicing : [4 5 6 7]
with steps :  [2 4 6 8]
reverse :  [10  9  8  7  6  5  4  3  2  1]
reverse slicing :  [6 7 8 9]


In [ ]:
# slicing in metrics

arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("specific element : ", arr_2d[1,2])
print("entire row : ", arr_2d[1])
print("entire row after slicing : \n", arr_2d[1::])   # 1:: and 1: is same
print("entire column : ", arr_2d[:, 1])               # :, means all rows
print("entire columns after slicing : \n", arr_2d[:, 1::])

specific element :  6
entire row :  [4 5 6]
entire row after slicing : 
 [[4 5 6]
 [7 8 9]]
entire column :  [2 5 8]
entire columns after slicing : 
 [[2 3]
 [5 6]
 [8 9]]


### Sorting

In [ ]:
unsorted = np.array([1,5,7,89,34,6,56,870])
print("sorted array : ", np.sort(unsorted))

unsorted_2d = np.array([[1,13,7,89],
                        [9,4,1,22],
                        [12,3,10,6]])
print("sorted array bt column : \n", np.sort(unsorted_2d, axis=0))
print("sorted array bt row : \n", np.sort(unsorted_2d, axis=1))

sorted array :  [  1   5   6   7  34  56  89 870]
sorted array bt column : 
 [[ 1  3  1  6]
 [ 9  4  7 22]
 [12 13 10 89]]
sorted array bt row : 
 [[ 1  7 13 89]
 [ 1  4  9 22]
 [ 3  6 10 12]]


### Filter

**Mask :**  
Numpy can filter mask in array like numbers[mask]  
Or expresion can directly passed in Array like numbers[numbers % 2 == 0]  

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("even numbers : ", even_numbers)


mask = numbers > 5
print("mask : ", numbers[mask])


even numbers :  [ 2  4  6  8 10]
mask :  [ 6  7  8  9 10]


**Fancy indexing VS np.where()**  
In Numpy indexes can be passed in Array like numbers[indices]  
np.Where gives indices from expresion.

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

indices = [0,3,5]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where : ", numbers[where_result])

[1 4 6]
(array([5, 6, 7, 8, 9]),)
NP where :  [ 6  7  8  9 10]


In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

conditional_array = np.where(numbers > 5 , numbers*4 , numbers)
print(conditional_array)

# In above example np.where can be explain by if else.
# if(numbers < 5){
#   numbers*4
# } else {
#   numbers}

conditional_array2 = np.where(numbers > 5 , "greater" , "less")
print(conditional_array2 )

[ 1  2  3  4  5 24 28 32 36 40]
['less' 'less' 'less' 'less' 'less' 'greater' 'greater' 'greater'
 'greater' 'greater']


### Array Compatibilty

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,"c"])

print("compatibilty shape : ", a.shape == b.shape == c.shape)
print("compatibilty data-type : ", a.dtype == b.dtype == c.dtype)

compatibilty shape :  True
compatibilty data-type :  False


### Adding Rows and Columns

In [ ]:
original = np.array([[1,2,3],[4,5,6]])
print("Original : \n", original)

new_row = np.array([7,8,9])
with_new_row = np.vstack((original, new_row))
print("with new row : \n", with_new_row)

new_column = np.array([[10],[11]])
with_new_column = np.hstack((original, new_column))
print("with new column : \n", with_new_column)


Original : 
 [[1 2 3]
 [4 5 6]]
with new row : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
with new column : 
 [[ 1  2  3 10]
 [ 4  5  6 11]]


# Practice

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Data Structure: [restaurant_id ,2021,2022,2023,2024]
seles_data = np.array([
    [1,150000,180000,220000,250000],
    [2,120000,140000,160000,190000],
    [3,200000,230000,260000,300000],
    [4,180000,210000,240000,270000],
    [5,160000,185000,205000,230000]
])

print("===Zomato seles analysis===")
print("seles data Shape : ", seles_data.shape)

===Zomato seles analysis===
seles data Shape :  (5, 5)


In [ ]:
print(seles_data[:, 1:]) #data without IDs

# seles per year
yearly_total = np.sum(seles_data[:, 1:], axis=0)
print("yearly total : \n", yearly_total)

# min seles per restaurant
min_seles = np.min(seles_data[:, 1:] , axis=1)
print("Min seles per restaurant : \n", min_seles)

# Max seles per year
Max_seles = np.max(seles_data[:, 1:] , axis=0)
print("Max seles per year : \n", Max_seles)

#Average seles per restaurant
average_seles = np.mean(seles_data[:, 1:], axis=1)
print("Average seles per restaurant : \n", average_seles)

#cumulative seles of restaurant
cumulative_seles = np.cumsum(seles_data[:, 1:], axis=1)
print("cumulative seles of restaurant : \n", cumulative_seles)

[[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]
yearly total : 
 [ 810000  945000 1085000 1240000]
Min seles per restaurant : 
 [150000 120000 200000 180000 160000]
Max seles per year : 
 [200000 230000 260000 300000]
Average seles per restaurant : 
 [200000. 152500. 247500. 225000. 195000.]
cumulative seles of restaurant : 
 [[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


In [ ]:
# Vector opration

vector1 = np.array([1,2,3,4,5])
vector2 = np.array([6,7,8,9,10])

print("vector addition : " , vector1 + vector2)

print("vector multiplication : " , vector1 * vector2)

print("vector Dot product : ", np.dot(vector1, vector2))

angle = np.arccos(np.dot(vector1, vector2) / (np.linalg.norm(vector1) * np.linalg.norm(vector2)))
print("angle between vectors : ", np.degrees(angle))

vector addition :  [ 7  9 11 13 15]
vector multiplication :  [ 6 14 24 36 50]
vector Dot product :  130
angle between vectors :  15.214413958603176


In [ ]:
restaurant_type = np.array(["pizza" , "burger" , "cafe", "indian"])
vectorized_upper = np.vectorize(str.upper)
print(vectorized_upper(restaurant_type))

monthly_Avg = seles_data[:, 1:] / 12
# HERE 12 IS SCELER NUMBER AND BRODCASTED SO 12 DIVIEDS ALL THE 25 VALUES
print("monthly Average : \n", np.around(monthly_Avg))

['PIZZA' 'BURGER' 'CAFE' 'INDIAN']
monthly Average : 
 [[12500. 15000. 18333. 20833.]
 [10000. 11667. 13333. 15833.]
 [16667. 19167. 21667. 25000.]
 [15000. 17500. 20000. 22500.]
 [13333. 15417. 17083. 19167.]]


# Practice 2

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Saving and extracing data in file from in numpy

array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.random.rand(3,3)
array3 = np.zeros((4,4))

np.save('array1.npy' , array1)
np.save('array2.npy' , array2)
np.save('array3.npy' , array3)

loaded_array = np.load('array1.npy')
print(loaded_array)

[[1 2 3]
 [4 5 6]]
